version: '3.8'

services:
  web:
    build: .
    container_name: electro_store
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=db_electro-store

  db:
    image: mysql:8.0
    container_name: db_electro-store
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_electro-store
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_data:/docker-entrypoint-initdb.d 

volumes:
  mysql_data:
